main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

ppwstory/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story7/', include('story7.urls')),
    path('buku/', include('story8.urls')),
    path('s9/', include('story9.urls')),
]

story7/urls.py
from django.urls import path

from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.home, name='home'),
]

story8/urls.py
from django.urls import path

from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.home, name='home'),
    path('cari', views.cari_buku, name='cari')
]

story9/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('login/', LoginView.as_view(template_name='story9/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='story9/logout.html'), name='logout'),
    path('profile/', views.profile, name='profile'),
]

main/models.py
from django.db import models

# Create your models here.

story7/models.py
from django.db import models

class Detail(models.Model):
    title = models.CharField(max_length=30)
    detail = models.TextField(max_length=300, default="Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium sit quisquam soluta, recusandae dolorem ea aspernatur deserunt exercitationem doloremque. Inventore facere sequi quos ex itaque, asperiores harum culpa commodi! Nemo!")
    color = models.CharField(max_length = 20, default='beige')

    def __str__(self):
        return self.title

def populate():
    titles = ['Current Activities', 'Achievements', 'Hobbies and Interests', 'Work Experiences']
    colors = ['salmon', 'hotpink', 'coral', 'peachpuff', 'plum', 'palegreen', 'aquamarine', 'bisque', 'lightgray', 'beige']
    for i in range(len(titles)):
        Detail.objects.create(title=titles[i], color=colors[i%10])

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.URLField(default="https://robohash.org/default?set=set4")
    full_name = models.CharField(max_length=50, null=True, blank=True)
    rep_points = models.IntegerField(default=0)
    instagram = models.CharField(max_length=50, null=True, blank=True)
    twitter = models.CharField(max_length=50, null=True, blank=True)
    line = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return f'{self.user.username}'

story9/forms.py
from django import forms
from crispy_forms.helper import FormHelper

from .models import Profile


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ['user', 'rep_points']
        widgets = {
            'full_name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'id': 'full-name',
                    'placeholder': 'Enter your full name',
                }
            ),
            'instagram': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'id': 'instagram',
                    'placeholder': 'Enter your Instagram account (e.g. @myigaccount)',
                }
            ),
            'twitter': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'id': 'twitter',
                    'placeholder': 'Enter your Twitter account (E.g. @mytwitteraccount)',
                }
            ),
            'line': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'id': 'line',
                    'placeholder': 'Enter your Line id (e.g terlalutampan)',
                }
            ),
            'avatar': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'id': 'image',
                    'placeholder': 'Enter an image URL',
                }
            ),
        }

    def __init__(self, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.fields['full_name'].label = "Full Name"
        self.fields['instagram'].label = "Instagram"
        self.fields['twitter'].label = "Twitter"
        self.fields['line'].label = "Line"

main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/home.html')

story7/views.py
from django.shortcuts import render
from .models import Detail

def home(request):
    details = Detail.objects.all()

    context = {
        'details' : details
    }

    return render(request, 'story7/index.html', context)

story8/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.utils.datastructures import MultiValueDictKeyError
import requests
import json


def home(request):

    context = {}
    return render(request, 'story8/index.html', context)


def cari_buku(request):
    try:
        url = 'https://www.googleapis.com/books/v1/volumes/?q=' + \
            request.GET['q'] + '&maxResults=25'
        ret = requests.get(url)
        data = json.loads(ret.content)

        return JsonResponse(data, safe=False)
    except MultiValueDictKeyError:
        return redirect('story8:home')

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import EditProfileForm
from django.contrib.auth.models import User


def home(request):
    context = {}
    return render(request, 'story9/home.html', context)


def signup(request):
    context = {}
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.add_message(
                request, messages.SUCCESS, f'Succesfully registered {username}. You can now log in.')
            return redirect('story9:login')
    else:
        form = UserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'story9/signup.html', context)


@login_required
def profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user.profile)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS,
                                 f'Successfully updated profile.')
            return redirect('story9:profile')
    else:
        form = EditProfileForm(instance=request.user.profile)
    context = {
        'form': form,
    }
    return render(request, 'story9/profile.html', context)

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
<div class="m-5 p-5 d-flex justify-content-around flex-wrap">
<a href="{% url 'story7:home' %}"><button class="btn btn-lg btn-outline-light">Story 7</button></a>
<a href="{% url 'story8:home' %}"><button class="btn btn-lg btn-outline-light">Story 8</button></a>
<a href="{% url 'story9:home' %}"><button class="btn btn-lg btn-outline-light">Story 9</button></a>
</div
{% endblock content %}

story7/templates/story7/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 7 | Accordion</title>
{% endblock meta %}

{% block content %}
<div class="container-fluid py-5">
  <div class="header">
    <div class="container d-flex justify-content-center">
      <img src="{% static 'img/logo.png' %}" alt="logo" id="logo" class="px-3">
      <h1>Story 7 : Accordion</h1>
    </div>
    <div class="container text-center pt-4">
      <a class="btn btn-outline-light" href="{% url 'main:home' %}">
        <i class="fas fa-arrow-left"></i>
        Back to home
      </a>
    </div>
  </div>
</div>

<div class="container ">
  <div class="text-center">
    <div class="wrapper">
      {% for detail in details %}
      <div class="acc-item">
        <div class="acc-header" style="background-color: {{detail.color}}">
          <div class="float-right">
            <i class="fas fa-chevron-up move-up"></i>&nbsp;
            <i class="fas fa-chevron-down move-down"></i>
          </div>
          <div class="title">
            {{detail.title}}
          </div>
        </div>
        <div class="acc-body">
          <p>{{detail.detail}}</p>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock content %}
{% block scripts %}
<script src="{% static 'js/accordion.js' %}"></script>
{% endblock scripts %}

story8/templates/story8/index.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>Story 8 | Cari Buku</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" href="{% static 'css/story8.css' %}" />
{% endblock meta %} {% block content %}
<div class="container-fluid py-5">
  <div class="header">
    <div class="container d-flex justify-content-center">
      <img
        src="{% static 'img/logo.png' %}"
        alt="logo"
        id="logo"
        class="px-3"
      />
      <h1>Cari Buku</h1>
    </div>
    <div class="container text-center pt-4">
      <a class="btn btn-outline-light" href="{% url 'main:home' %}">
        <i class="fas fa-arrow-left"></i>
        Back to home
      </a>
    </div>
  </div>
</div>
<div class="container">
  <div class="form-row">
    <div class="form-group col">
      <input
        class="form-control"
        id="keyword"
        placeholder="masukkan kata kunci"
        type="text"
      />
    </div>
    <div class="form-group col-auto text-right">
      <button id="list-view" class="btn btn-dark" disabled>
        <i class="fas fa-list"></i>
      </button>
      <button id="table-view" class="btn btn-dark">
        <i class="fas fa-table"></i>
      </button>
    </div>
  </div>
  <hr />
  <br />
  <div id="daftar-isi"></div>
</div>
{% endblock content %} {% block scripts %}
<script>
  var array_items = {};
  var use_table_view = false;
  function draw_table() {
    $("#daftar-isi").empty();
    if (array_items != null) {
      $("#daftar-isi").append(
        '<table class="table table-dark table-responsive-lg"><thead><tr><th><i class="fas fa-link"></i></th><th scope="col">Cover</th><th scope="col">Judul</th><th scope="col">Author</th><th>Publisher</th><th>Published</th><th scope="col">ISBN13</th></tr></thead><tbody></tbody></table>'
      );
      for (i = 0; i < array_items.length; i++) {
        var judul = array_items[i].volumeInfo.title;
        try {
          gambar = array_items[i].volumeInfo.imageLinks.smallThumbnail;
        } catch {
          gambar = "{% static 'img/noimage.png' %}";
        }
        try {
          author = array_items[i].volumeInfo.authors;
          if (author == null) {
            author = "-";
          }
        } catch {
          author = "-";
        }
        try {
          var isbn = "-";
          var temp = array_items[i].volumeInfo.industryIdentifiers;
          if (temp != null) {
            for (j = 0; j < temp.length; j++) {
              if (temp[j].type == "ISBN_13") {
                isbn = temp[j].identifier;
                break;
              }
            }
          }
        } catch {
          isbn = "-";
        }
        try {
          publisher = array_items[i].volumeInfo.publisher;
          if (publisher == null) {
            publisher = "-";
          }
        } catch {
          publisher = "-";
        }
        try {
          publishedDate = array_items[i].volumeInfo.publishedDate;
          if (publishedDate == null) {
            publishedDate = "-";
          }
        } catch {
          publishedDate = "-";
        }
        try {
          preview = array_items[i].volumeInfo.previewLink;
          if (preview == null) {
            preview = "#";
          }
        } catch {
          preview = "#";
        }
        $("tbody").append(
          '<tr><td><a class="button btn-sm btn-dark" href="' +
            preview +
            '" target="_blank"><i class="fas fa-external-link-alt"></i></a></td><td><img src="' +
            gambar +
            '" alt="' +
            judul +
            '" class="img-fluid book-img-table"></td><td>' +
            judul +
            "</td><td>" +
            author +
            "</td><td>" +
            publisher +
            "</td><td>" +
            publishedDate +
            "</td><td>" +
            isbn +
            "</td></tr>"
        );
      }
      $("#daftar-isi").append("<small>(-) : data tidak tersedia </small>");
    } else {
      $("#daftar-isi").append("<p>Hasil tidak ditemukan</p>");
    }
  }
  function draw_list() {
    $("#daftar-isi").empty();
    if (array_items != null) {
      $("#daftar-isi").append('<hr class="hr">');
      for (i = 0; i < array_items.length; i++) {
        judul = array_items[i].volumeInfo.title;
        try {
          gambar = array_items[i].volumeInfo.imageLinks.smallThumbnail;
        } catch {
          gambar = "{% static 'img/noimage.png' %}";
        }
        try {
          author = "by " + array_items[i].volumeInfo.authors.join(", ");
        } catch {
          author = "by Unknown";
        }
        try {
          textSnippet = array_items[i].volumeInfo.description.replace(
            /^(.{150}[^\s]*).*/,
            "$1"
          );
          if (
            textSnippet.length < array_items[i].volumeInfo.description.length
          ) {
            textSnippet += "...";
          }
        } catch {
          textSnippet = "";
        }
        try {
          preview = array_items[i].volumeInfo.previewLink;
          if (preview == null) {
            preview = "#";
          }
        } catch {
          preview = "#";
        }
        $("#daftar-isi").append(
          '<div class="card my-1"><div class="row no-gutters"><div class="col-auto"><img src="' +
            gambar +
            '" class="img-fluid book-img" alt="' +
            judul +
            '"></div><div class="col pl-1"><div class="card-block px-2"><h5 class="card-title">' +
            judul +
            '</h5><p class="card-text">' +
            author +
            "</p><small>" +
            textSnippet +
            '</small><p class="mt-2"><a class="button btn-dark btn-sm" target="_blank" href="' +
            preview +
            '"><i class="fas fa-external-link-alt"></i> preview</a></p></div></div></div><hr class="hr"></div>'
        );
      }
    } else {
      $("#daftar-isi").append("<p>Hasil tidak ditemukan</p>");
    }
  }
  function delay(fn, ms) {
    let timer = 0;
    return function (...args) {
      clearTimeout(timer);
      timer = setTimeout(fn.bind(this, ...args), ms || 0);
    };
  }
  $("#keyword").keyup(
    delay(function () {
      var ketikan = $("#keyword").val();
      console.log(ketikan);
      //panggil dengan ajax
      $.ajax({
        url: "{% url 'story8:cari' %}?q=" + ketikan,
        success: function (data) {
          array_items = data.items;
          if (use_table_view == false) {
            draw_list();
          } else {
            draw_table();
          }
        },
      });
    }, 500)
  );
  $("#table-view").click(function () {
    use_table_view = true;
    $("#list-view").attr("disabled", false);
    $(this).attr("disabled", true);
    draw_table();
  });
  $("#list-view").click(function () {
    use_table_view = false;
    $("#table-view").attr("disabled", false);
    $(this).attr("disabled", true);
    draw_list();
  });
</script>
{% endblock scripts %}

story8/templates/story8/table.html
<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">Cover</th>
      <th scope="col">Judul</th>
      <th scope="col">Author</th>
      <th scope="col">ISBN</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>

story9/templates/story9/home.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>Story 9</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" href="{% static 'css/story9.css' %}" />
{% endblock meta %} {% block content %} {% include 'story9/navbar9.html' %} {% include 'story9/messages.html' %}
<div class="container my-5">
  <h1>
    Hello there{% if user.is_authenticated %}, {{user.username}}{%endif %}!
  </h1>
  {% if user.is_authenticated %}
  <h3>You can now see your profile <a href="{% url 'story9:profile' %}">here</a>.</h3>
  {% else %}
  <br>
  <h3>You need to log in to use all of the features</h3>
  <div class="d-flex mt-5">
    <a href="{% url 'story9:login' %}"><button class="btn btn-lg btn-dark">Log In</button></a>
    &nbsp;&nbsp;&nbsp;
    <a href="{% url 'story9:signup' %}"<button class="btn btn-lg btn-outline-secondary">Sign Up</button></a>
  </div>
  {% endif %}
</div>
{% endblock content %} {% block scripts %} {% endblock scripts %}

story9/templates/story9/login.html
{% extends 'base.html' %} {% load static %} {% load crispy_forms_tags %} &nbsp;
{%block meta %}
<title>Story 9</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" href="{% static 'css/story9.css' %}" />
{% endblock meta %} {% block content %}
{% include 'story9/navbar9.html' %}
{% include 'story9/messages.html' %}
<div class="container">
  <div class="card signup p-4 mx-auto my-5">
    <div class="form">
      <form
        class="d-flex flex-column justify-content-center"
        action=""
        method="POST"
      >
        <legend class="text-center">
          Log In
        </legend>
        <br>
        {% csrf_token %}
        <div>{{ form|crispy }}</div>
        <br />
        <button
          id="loginButton"
          class="btn btn-dark mb-3"
          type="submit"
        >
          Login
        </button>
      </form>
    </div>
    <div class="card-footer text-center">
      <small
        ><a href="{% url 'story9:signup' %}">No account? Sign Up!</a>
      </small>
    </div>
  </div>
</div>
{% endblock content %} {% block scripts %} {% endblock scripts %}

story9/templates/story9/logout.html
{% extends 'base.html' %} {% load static %} {% load crispy_forms_tags %} &nbsp;
{%block meta %}
<title>Story 9</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" href="{% static 'css/story9.css' %}" />
{% endblock meta %} {% block content %} {% include 'story9/navbar9.html' %} {% include 'story9/messages.html' %}
<div class="container">
  <div class="card signup p-4 mx-auto my-5">
    <legend class="text-center">You have successfully signed out</legend>
    <div class="card-footer text-center">
      <small><a href="{% url 'story9:login' %}">Log in again?</a> </small>
    </div>
  </div>
</div>
{% endblock content %} {% block scripts %} {% endblock scripts %}

story9/templates/story9/messages.html
{% if messages %}
<ul class="messages container mt-4 mb-0" style="list-style: none">
  {% for message in messages %}
  <li {% if message.tags %} class="alert alert-{{ message.tags }} alert-dismissible fade show" {% endif %}>
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </li>
  {% endfor %}
</ul>
{% endif %}

story9/templates/story9/navbar9.html
{% load static %}
<nav class="navbar navbar-dark bg-dark navbar-expand-lg shadow">
  <a class="navbar-brand" href="#">
    <img
      src="{% static 'img/logo.png' %}"
      width="30"
      height="30"
      class="d-inline-block align-top"
      alt=""
    />
    AuthApp
  </a>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarNavAltMarkup"
    aria-controls="navbarNavAltMarkup"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav mr-auto">
      <a class="nav-item nav-link" href="{% url 'story9:home' %}">Home</a>
    </div>
    <div class="navbar-nav ml-auto">
      {% if user.is_authenticated %}
      <div class="nav-item dropdown">
        <a
          class="nav-link dropdown-toggle"
          href="#"
          id="navbarDropdown"
          role="button"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false"
        >
          My Account
        </a>
        <div
          class="dropdown-menu dropdown-menu-right bg-dark"
          aria-labelledby="navbarDropdown"
        >
          <a
            class="nav-item nav-link d-flex justify-content-between align-items-center px-3"
            href="{% url 'story9:profile' %}"
            >See Profile<i class="far fa-user-circle"></i
          ></a>
          <div
            class="nav-item nav-link d-flex justify-content-between align-items-center px-3"
            id="editProfile"
            data-toggle="modal"
            data-target="#edit"
            >Edit Profile<i class="far fa-edit"></i
          ></div>
          <div class="dropdown-divider"></div>
          <a
            class="nav-item nav-link d-flex justify-content-between align-items-center px-3"
            href="{% url 'story9:logout' %}"
            >Logout<i class="fas fa-sign-out-alt"></i
          ></a>
        </div>
      </div>
      {% else %}
      <a class="nav-item nav-link" href="{% url 'story9:login' %}">Log In</a>
      <a class="nav-item nav-link" href="{% url 'story9:signup' %}">Sign Up</a>
      {% endif %}
    </div>
  </div>
</nav>

story9/templates/story9/profile.html
{% extends 'base.html' %} {% load static %} {% load crispy_forms_tags %} &nbsp;
{%block meta %}
<title>Story 9</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" href="{% static 'css/story9.css' %}" />
{% endblock meta %} {% block content %} {% include 'story9/navbar9.html' %}
&nbsp; {% include 'story9/messages.html' %}
<div class="container my-3">
  <div class="row">
    <div class="col-md-3 d-flex flex-column justify-content-center">
      <img
        class="img-fluid img-thumbnail"
        src="{{user.profile.avatar}}"
        alt="{{user.username}}'s avatar"
      />
      <div
        id="editProfile"
        data-toggle="modal"
        data-target="#edit"
        type="button"
        class="btn btn-dark mt-2"
      >
        Edit Profile
      </div>

      <!--<a href=""> <button class="btn btn-dark">Randomize avatar</button> </a>-->
    </div>
    <div class="col">
      {% if user.profile.full_name %}
      <h1>Hello, {{user.profile.full_name}}!</h1>
      {% else %}
      <h1>Hello, {{user.username}}!</h1>
      {% endif %}
      <p>id: {{user.username}}</p>
      <h4>
        <i class="fab fa-instagram"></i> {% if user.profile.instagram %}
        {{user.profile.instagram}} {% else %} - {% endif %}<br />
        <i class="fab fa-twitter-square"></i> {% if user.profile.twitter %}
        {{user.profile.twitter}} {% else %} - {% endif %} <br />
        <i class="fab fa-line"></i> {% if user.profile.line %}
        {{user.profile.line}} {% else %} - {% endif %}
      </h4>
    </div>
  </div>
</div>
<!-- Modal -->
<div
  class="modal fade"
  id="edit"
  tabindex="-1"
  role="dialog"
  aria-labelledby="exampleModalCenterTitle"
  aria-hidden="true"
>
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" style="color: black">Edit User Profile</h5>
        <button
          type="button"
          class="close"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form
        action="{% url 'story9:profile' %}"
        method="POST"
        style="color: black"
      >
        <div class="modal-body">{% csrf_token %} {{ form|crispy }}</div>
        <div class="modal-footer">
          <button id="saveEdit" type="submit" class="btn btn-dark mr-2">
            Save
          </button>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">
            Close
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
<!-- End Modal -->
{% endblock content %} {% block scripts %} {% endblock scripts %}

story9/templates/story9/signup.html
{% extends 'base.html' %} {% load static %} {% load crispy_forms_tags %} &nbsp;
{% block meta %}
<title>Story 9</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" href="{% static 'css/story9.css' %}" />
{% endblock meta %} {% block content %}
{% include 'story9/navbar9.html' %}
{% include 'story9/messages.html' %}
<div class="container">
  <div class="card signup p-4 mx-auto my-5">
    <div class="signupform">
      <form
        class="d-flex flex-column justify-content-center"
        action=""
        method="POST"
      >
        <legend class="text-center">Create an account</legend>
        <br />
        {% csrf_token %}
        <div>{{ form|crispy }}</div>
        <br />
        <button
          id="loginButton"
          class="btn btn-dark mb-3"
          type="submit"
        >
          Sign Up
        </button>
      </form>
    </div>
    <div class="card-footer text-center">
      <small
        ><a href="{% url 'story9:login' %}">Already have an account? Login.</a>
      </small>
    </div>
  </div>
</div>
{% endblock content %} {% block scripts %} {% endblock scripts %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="{% static 'img/logo.png' %}" type="image/x-icon">
  <!--Bootstrap & Project-wide CSS-->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <!--Fontawesome 5-->
  <script src="https://kit.fontawesome.com/8a455c0870.js" crossorigin="anonymous"></script>
  <!--JQuery & Bootstrap JS-->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  <!--Other Meta-->
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>
{% block scripts %}
{% endblock scripts %}